apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyRestrictedNamespaceAccess
metadata:
  name: denyrestrictednamespaceaccess
spec:
  match:
    namespaces:
      - kube-system
  rules:
  - operations: ["*"]