apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: denyrestrictednamespaceaccess
spec:
  crd:
    spec:
      names:
        kind: DenyRestrictedNamespaceAccess
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package DenyNamespace

        violation[{"msg": msg}] {
          not startswith(input.review.userInfo.username, "system:")
          msg := sprintf("you cant use namespace: %v", [input.review.object.metadata.namespace])
        }